### ISSUE TITLE
运行出现问题

### ISSUE THREAD

**Issue by wemindful** [mickkky/XML-Augment#3]
Traceback (most recent call last):
  File "F:/CTtrain/data-augmentation/Augmentation.py", line 145, in <module>
    bndbox = read_xml_annotation(XML_DIR, name)
  File "F:/CTtrain/data-augmentation/Augmentation.py", line 30, in read_xml_annotation
    bndbox = root.find('object').find('bndbox')
AttributeError: 'NoneType' object has no attribute 'find'

2：
 数据增强只有正样本 没有对于负样本的增强，建议解决这个问题

**Comment by wemindful** [comment]
我已经自己完成了 修改

**Comment by RongrongTian** [comment]
您好，我也遇到这个，想想问问您怎么解决的，谢谢您
